#!/usr/bin/env node

/**
 * Quick Setup Script for Google Calendar API
 * This script guides you through the setup process interactively
 * 
 * Run with: node scripts/quick-setup.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function main() {
  console.log('\n🚀 Google Calendar API Quick Setup\n');
  console.log('=' .repeat(50));
  console.log('This script will help you set up Google Calendar API integration.');
  console.log('You\'ll need to complete some steps in Google Cloud Console.\n');

  // Check if .env.local exists
  const envPath = path.join(__dirname, '..', '.env.local');
  if (fs.existsSync(envPath)) {
    const overwrite = await question('⚠️  .env.local already exists. Overwrite? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  console.log('\n📋 Step 1: Google Cloud Console');
  console.log('-'.repeat(50));
  console.log('1. Go to: https://console.cloud.google.com/');
  console.log('2. Create a new project (or select existing)');
  console.log('3. Enable Google Calendar API:');
  console.log('   - Navigate to: APIs & Services > Library');
  console.log('   - Search: "Google Calendar API"');
  console.log('   - Click: Enable\n');
  await question('Press Enter when done...');

  console.log('\n📋 Step 2: Create Service Account');
  console.log('-'.repeat(50));
  console.log('1. Go to: APIs & Services > Credentials');
  console.log('2. Click: Create Credentials > Service Account');
  console.log('3. Name: peerpoint-calendar-service');
  console.log('4. Description: Service account for canceling calendar events');
  console.log('5. Click: Create and Continue');
  console.log('6. Skip optional steps, click: Done\n');
  await question('Press Enter when done...');

  console.log('\n📋 Step 3: Download Service Account Key');
  console.log('-'.repeat(50));
  console.log('1. Click on the service account you just created');
  console.log('2. Go to: Keys tab');
  console.log('3. Click: Add Key > Create new key');
  console.log('4. Select: JSON format');
  console.log('5. Download the JSON file\n');
  
  const jsonPath = await question('Enter the path to your downloaded JSON file: ');

  if (!fs.existsSync(jsonPath)) {
    console.error('❌ File not found:', jsonPath);
    rl.close();
    return;
  }

  // Read and parse JSON
  let jsonData;
  try {
    const jsonContent = fs.readFileSync(jsonPath, 'utf-8');
    jsonData = JSON.parse(jsonContent);
  } catch (error) {
    console.error('❌ Error reading JSON file:', error.message);
    rl.close();
    return;
  }

  const serviceAccountEmail = jsonData.client_email;
  const privateKey = jsonData.private_key;

  if (!serviceAccountEmail || !privateKey) {
    console.error('❌ Invalid JSON file. Missing client_email or private_key.');
    rl.close();
    return;
  }

  console.log('\n✅ Credentials extracted successfully!');
  console.log(`   Service Account: ${serviceAccountEmail}\n`);

  // Format private key for .env file
  const formattedKey = privateKey.replace(/\n/g, '\\n');

  // Create .env.local
  const envContent = `# Google Calendar API Configuration
# Generated by quick-setup script on ${new Date().toISOString()}

GOOGLE_SERVICE_ACCOUNT_EMAIL=${serviceAccountEmail}
GOOGLE_PRIVATE_KEY="${formattedKey}"
`;

  fs.writeFileSync(envPath, envContent);
  console.log('✅ Created .env.local file\n');

  console.log('📋 Step 4: Share Calendars');
  console.log('-'.repeat(50));
  console.log('For EACH tutor\'s Google Calendar:');
  console.log('1. Open Google Calendar');
  console.log('2. Go to: Settings > Settings for my calendars');
  console.log('3. Select the calendar used for appointments');
  console.log('4. Click: Share with specific people');
  console.log(`5. Add this email: ${serviceAccountEmail}`);
  console.log('6. Permission: "Make changes to events"');
  console.log('7. Click: Send\n');
  await question('Press Enter when done...');

  console.log('\n✅ Setup Complete!\n');
  console.log('Next steps:');
  console.log('1. Restart your dev server: npm run dev');
  console.log('2. Test by rejecting a booking from the admin panel');
  console.log('3. Verify that calendar events are canceled\n');

  // Try to validate
  console.log('Running validation...\n');
  try {
    const { validateSetup } = require('./validate-calendar-setup.js');
    validateSetup();
  } catch (error) {
    console.log('⚠️  Could not run validation automatically');
    console.log('   Run manually with: npm run validate-calendar\n');
  }

  rl.close();
}

main().catch((error) => {
  console.error('❌ Error:', error.message);
  rl.close();
  process.exit(1);
});
