#!/bin/bash

# Google Calendar API Automated Setup Script
# This script helps automate the setup process

set -e

echo "🚀 Google Calendar API Setup Script"
echo "===================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if .env.local exists
if [ -f ".env.local" ]; then
    echo -e "${YELLOW}⚠️  .env.local already exists${NC}"
    read -p "Do you want to overwrite it? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 1
    fi
fi

echo "📋 Step 1: Google Cloud Console Setup"
echo "--------------------------------------"
echo ""
echo "Please complete these steps in your browser:"
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Create a new project (or select existing)"
echo "3. Enable Google Calendar API:"
echo "   - Navigate to: APIs & Services > Library"
echo "   - Search: 'Google Calendar API'"
echo "   - Click: Enable"
echo ""
read -p "Press Enter when you've enabled the Google Calendar API..."

echo ""
echo "📋 Step 2: Create Service Account"
echo "----------------------------------"
echo ""
echo "Please complete these steps:"
echo "1. Go to: APIs & Services > Credentials"
echo "2. Click: Create Credentials > Service Account"
echo "3. Name: peerpoint-calendar-service"
echo "4. Description: Service account for canceling calendar events"
echo "5. Click: Create and Continue"
echo "6. Skip optional steps, click: Done"
echo ""
read -p "Press Enter when you've created the service account..."

echo ""
echo "📋 Step 3: Generate Service Account Key"
echo "----------------------------------------"
echo ""
echo "Please complete these steps:"
echo "1. Click on the service account you just created"
echo "2. Go to: Keys tab"
echo "3. Click: Add Key > Create new key"
echo "4. Select: JSON format"
echo "5. Download the JSON file"
echo ""
read -p "Press Enter when you've downloaded the JSON file..."

echo ""
echo "📋 Step 4: Extract Credentials"
echo "-------------------------------"
echo ""
read -p "Enter the path to your downloaded JSON file: " JSON_FILE_PATH

if [ ! -f "$JSON_FILE_PATH" ]; then
    echo -e "${RED}❌ File not found: $JSON_FILE_PATH${NC}"
    exit 1
fi

# Extract credentials from JSON
SERVICE_ACCOUNT_EMAIL=$(grep -o '"client_email": "[^"]*' "$JSON_FILE_PATH" | cut -d'"' -f4)
PRIVATE_KEY=$(grep -o '"private_key": "[^"]*' "$JSON_FILE_PATH" | cut -d'"' -f4)

if [ -z "$SERVICE_ACCOUNT_EMAIL" ] || [ -z "$PRIVATE_KEY" ]; then
    echo -e "${RED}❌ Could not extract credentials from JSON file${NC}"
    echo "Please check that the file is a valid service account JSON file."
    exit 1
fi

echo ""
echo -e "${GREEN}✅ Credentials extracted successfully${NC}"
echo "   Service Account: $SERVICE_ACCOUNT_EMAIL"
echo ""

# Format private key for .env file (escape newlines)
FORMATTED_KEY=$(echo "$PRIVATE_KEY" | sed 's/\\n/\\\\n/g')

# Create .env.local file
cat > .env.local << EOF
# Google Calendar API Configuration
# Generated by setup script on $(date)

GOOGLE_SERVICE_ACCOUNT_EMAIL=$SERVICE_ACCOUNT_EMAIL
GOOGLE_PRIVATE_KEY="$FORMATTED_KEY"
EOF

echo -e "${GREEN}✅ Created .env.local file${NC}"
echo ""

echo "📋 Step 5: Share Calendars"
echo "---------------------------"
echo ""
echo "For EACH tutor's Google Calendar:"
echo "1. Open Google Calendar"
echo "2. Go to: Settings > Settings for my calendars"
echo "3. Select the calendar used for appointments"
echo "4. Click: Share with specific people"
echo "5. Add this email: $SERVICE_ACCOUNT_EMAIL"
echo "6. Permission: 'Make changes to events'"
echo "7. Click: Send"
echo ""
read -p "Press Enter when you've shared the calendars..."

echo ""
echo "📋 Step 6: Validate Setup"
echo "-------------------------"
echo ""
echo "Running validation script..."
echo ""

if command -v node &> /dev/null; then
    node scripts/validate-calendar-setup.js
else
    echo -e "${YELLOW}⚠️  Node.js not found. Skipping validation.${NC}"
    echo "You can run validation later with: npm run validate-calendar"
fi

echo ""
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo ""
echo "Next steps:"
echo "1. Restart your dev server: npm run dev"
echo "2. Test by rejecting a booking from the admin panel"
echo "3. Verify that calendar events are canceled"
echo ""
